# Generated by Django 4.2.2 on 2023-06-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openinghourmodel",
            name="end_time",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="openinghourmodel",
            name="start_time",
            field=models.CharField(max_length=100),
        ),
    ]
