# Generated by Django 4.2.2 on 2023-06-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0002_alter_openinghourmodel_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openingtimeexceptionmodel",
            name="end_datetime",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="openingtimeexceptionmodel",
            name="start_datetime",
            field=models.DateField(),
        ),
    ]
