# Generated by Django 4.2.2 on 2023-06-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0003_alter_openingtimeexceptionmodel_end_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practicemodel",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="staffmodel",
            name="job_title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
