# Generated by Django 4.2.2 on 2023-06-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0004_alter_practicemodel_slug_alter_staffmodel_job_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientmodel",
            name="city",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="patientmodel",
            name="country",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="patientmodel",
            name="state",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="patientmodel",
            name="zip_code",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="practicemodel",
            name="city",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="practicemodel",
            name="country",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="practicemodel",
            name="state",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="practicemodel",
            name="zip_code",
            field=models.CharField(max_length=100),
        ),
    ]
