# Generated by Django 4.2.2 on 2023-07-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0006_alter_appointmentmodel_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescriptionmodel",
            name="pharmacy_name",
            field=models.CharField(max_length=1000),
        ),
    ]
