# Generated by Django 4.2.2 on 2023-07-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0009_remove_prescriptionmodel_prescription_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prescriptionlineitemmodel",
            old_name="quantiy",
            new_name="quantity",
        ),
    ]
