# Generated by Django 4.2.2 on 2023-07-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0010_rename_quantiy_prescriptionlineitemmodel_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentmodel",
            name="state",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="patientverificationmodel",
            name="state",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="prescriptionmodel",
            name="state",
            field=models.CharField(max_length=100),
        ),
    ]
