# Generated by Django 4.2.2 on 2023-07-10 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0015_prescriptioncommentmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentmodel",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="rest_api.staffmodel",
            ),
        ),
        migrations.AddField(
            model_name="prescriptionmodel",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="rest_api.staffmodel",
            ),
        ),
    ]
