# Generated by Django 4.2.2 on 2023-07-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0016_appointmentmodel_assigned_to_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffmodel",
            name="is_bookable",
        ),
        migrations.RemoveField(
            model_name="staffmodel",
            name="is_doctor",
        ),
    ]
