# Generated by Django 4.2.2 on 2023-07-19 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0017_remove_staffmodel_is_bookable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffmodel",
            name="practice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rest_api.practicemodel",
            ),
            preserve_default=False,
        ),
    ]
