# Generated by Django 4.2.2 on 2023-08-23 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0023_patientpracticemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeFeatureFlagModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flag_id", models.CharField(max_length=100)),
                ("flag_value", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "practice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_practice_related",
                        related_query_name="%(app_label)s_%(class)s_practices",
                        to="rest_api.practicemodel",
                    ),
                ),
            ],
        ),
    ]
