# Generated by Django 4.2.2 on 2023-08-23 08:33
from django.apps import apps
from django.db import migrations

PracticeFeatureFlagModel = apps.get_model("rest_api", "PracticeFeatureFlagModel")
PracticeModel = apps.get_model("rest_api", "PracticeModel")


def forwards_func(apps, schema_editor):
    all_practices = PracticeModel.objects.all()
    for practice in all_practices:
        PracticeFeatureFlagModel.objects.create(
            practice=practice, flag_id="appointment_request", flag_value=False
        )
        PracticeFeatureFlagModel.objects.create(
            practice=practice, flag_id="prescription_request", flag_value=False
        )


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0024_practicefeatureflagmodel"),
    ]

    operations = [migrations.RunPython(forwards_func)]
