# Generated by Django 4.2.2 on 2023-08-26 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0025_practicefeatureflagmodel_backfill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="availableappointmentmodel",
            name="appointment_type",
        ),
        migrations.AddField(
            model_name="availableappointmentmodel",
            name="schedule_release_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="availableappointmentmodel",
            name="team_member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="rest_api.teammembermodel",
            ),
        ),
    ]
