# Generated by Django 4.2.2 on 2023-09-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0026_remove_availableappointmentmodel_appointment_type_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="availableappointmentmodel",
            constraint=models.UniqueConstraint(
                fields=("team_member", "start_time", "end_time", "practice"),
                name="unique_available_appointment",
            ),
        ),
    ]
