# Generated by Django 4.2.2 on 2023-09-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0028_bookinginvitemodel_bookingmodel_bookingstatelogmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BookingStateLogModel",
        ),
    ]
