version: "3.9"
services:
  base:
    env_file:
      - .env
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_URL: ${CELERY_RESULT_URL}
      CHANNELS_URLS: ${CHANNELS_URLS}
      ELASTIC_SEARCH_HOST: ${ELASTIC_SEARCH_HOST}
      AUTH_DOMAIN: ${AUTH_DOMAIN}
      AUTH_IDENTIFIER: ${AUTH_IDENTIFIER}
      DD_ENV: ${DD_ENV}
      DD_TRACE_ENABLED: ${DD_TRACE_ENABLED}
      FLOWER_USER: ${FLOWER_USER}
      FLOWER_PASSWORD: ${FLOWER_PASSWORD}
      DJANGO_HOT_RELOAD: ${DJANGO_HOT_RELOAD}
      GMAPS_API_KEY: ${GMAPS_API_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      BUCKET_USERNAME: ${BUCKET_USERNAME}
      BUCKET_KEY: ${BUCKET_KEY}
      BUCKET_SECRET: ${BUCKET_SECRET}
      BUCKET_ENDPOINT: ${BUCKET_ENDPOINT}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      CELERY_QUEUE: ${CELERY_QUEUE}
