apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker-deployment
  namespace: default
  labels:
    app: celery-worker-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: celery-worker-app
  template:
    metadata:
      labels:
        app: celery-worker-app
    spec:
      volumes:
        - name: celery-logs
          hostPath:
            path: /var/logs/celery-worker/
      terminationGracePeriodSeconds: 3600
      nodeSelector:
        nodeType: general-purpose
      imagePullSecrets:
        - name: docker-cfg
      containers:
        - name: celery-worker-docker-image
          image: DOCKER_REGISTRY_URL:DOCKER_VERSION
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: celery-logs
              mountPath: /logs/
          resources:
            requests:
              cpu: "100m"
              memory: "500M"
            limits:
              cpu: "500m"
              memory: "1000M"
          readinessProbe:
            exec:
              command: ["python", "django_project/celery_readiness.py"]
            initialDelaySeconds: 120
            periodSeconds: 60
          livenessProbe:
            exec:
              command: ["python", "django_project/celery_worker_liveness.py"]
            initialDelaySeconds: 120
            periodSeconds: 60

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: celery-rabbitmq-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: celery-worker-deployment
  pollingInterval: 15
  cooldownPeriod: 200
  maxReplicaCount: 10
  minReplicaCount: 1
  triggers:
    - type: rabbitmq
      metadata:
        hostFromEnv: RABBITMQ_URL
        queueName: celery
        mode: QueueLength
        value: "10"
